sudo:          false
language:      node_js
node_js:
  - "node"
install:       npm install
script:
  - npm test
  - gulp
cache:
  directories:
    - node_modules

# Disqus
discus-identifier: skyksit-github-io # add your discus identifier
